apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-pipelines
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/ocppe/gitops-hub.git
    targetRevision: main
    path: operators/openshift-pipelines
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
