apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-pipelines
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/ocppe/gitops-hub.git
    targetRevision: main
    path: cluster-config/pipelines
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
