apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-webhook-secret
  namespace: ci-pipelines
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: github-webhook-secret
    creationPolicy: Owner
  data:
    - secretKey: webhook-secret
      remoteRef:
        key: ocppe/ci-pipelines
        property: github-webhook-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: quay-credentials
  namespace: ci-pipelines
  annotations:
    tekton.dev/docker-0: https://quay.io
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: quay-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "quay.io": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  data:
    - secretKey: username
      remoteRef:
        key: ocppe/ci-pipelines
        property: quay-username
    - secretKey: password
      remoteRef:
        key: ocppe/ci-pipelines
        property: quay-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-credentials
  namespace: ci-pipelines
  annotations:
    tekton.dev/git-0: https://github.com
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: git-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: ocppe/ci-pipelines
        property: git-username
    - secretKey: password
      remoteRef:
        key: ocppe/ci-pipelines
        property: git-password
