apiVersion: v1
kind: Namespace
metadata:
  name: ci-pipelines
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-sa
  namespace: ci-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-sa-admin
subjects:
  - kind: ServiceAccount
    name: pipeline-sa
    namespace: ci-pipelines
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
