apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci-pipeline
  namespace: ci-pipelines
spec:
  description: Generic CI pipeline that detects app type and runs appropriate build
  params:
    - name: git-url
      description: Git repository URL
      type: string
    - name: git-revision
      description: Git revision (branch, tag, or commit)
      type: string
      default: "main"
    - name: image-registry
      description: Container registry
      type: string
      default: "quay.io"
    - name: image-repository
      description: Image repository
      type: string
      default: "ocppe"
    - name: run-tests
      description: Whether to run tests
      type: string
      default: "true"
  workspaces:
    - name: shared-workspace
    - name: dockerconfig
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: subdirectory
          value: source
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: detect-app-type
      taskRef:
        name: detect-app-type
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: shared-workspace

    # Quarkus build path
    - name: test-quarkus
      taskRef:
        name: test-quarkus
      runAfter:
        - detect-app-type
      when:
        - input: $(tasks.detect-app-type.results.app-type)
          operator: in
          values: ["quarkus"]
        - input: $(params.run-tests)
          operator: in
          values: ["true"]
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build-quarkus
      taskRef:
        name: build-quarkus
      runAfter:
        - detect-app-type
      when:
        - input: $(tasks.detect-app-type.results.app-type)
          operator: in
          values: ["quarkus"]
      params:
        - name: maven-goals
          value: ["package", "-DskipTests"]
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build-push-image
      taskRef:
        name: build-push-image
      runAfter:
        - build-quarkus
      when:
        - input: $(tasks.detect-app-type.results.app-type)
          operator: in
          values: ["quarkus"]
      params:
        - name: image-registry
          value: $(params.image-registry)
        - name: image-repository
          value: $(params.image-repository)
        - name: image-name
          value: $(tasks.detect-app-type.results.app-name)
        - name: image-tag
          value: $(params.git-revision)-$(tasks.git-clone.results.commit)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig

  results:
    - name: app-type
      description: Detected application type
      value: $(tasks.detect-app-type.results.app-type)
    - name: app-name
      description: Application name
      value: $(tasks.detect-app-type.results.app-name)
    - name: image-url
      description: Built image URL
      value: $(tasks.build-push-image.results.image-url)
