apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ci-pipeline-template
  namespace: ci-pipelines
spec:
  params:
    - name: git-url
      description: Git repository URL
    - name: git-revision
      description: Git revision
      default: main
    - name: git-repo-name
      description: Repository name
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: ci-pipeline-$(tt.params.git-repo-name)-
        namespace: ci-pipelines
      spec:
        pipelineRef:
          name: ci-pipeline
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: image-registry
            value: quay.io
          - name: image-repository
            value: ocppe
          - name: run-tests
            value: "true"
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: dockerconfig
            secret:
              secretName: quay-credentials
        serviceAccountName: pipeline-sa
